<a href="https://colab.research.google.com/github/shallabhkhera/NPTEL-Essential-Mathematics-for-Machine-Learning/blob/main/Lec1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A=np.array([[2,-2,3], [1,1,1],[1,3,-1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [3]:
values, vectors = np.linalg.eig(A)

In [4]:
print(values)

[ 3.  1. -2.]


In [5]:
print(vectors)

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [6]:
B=np.array([[2,0,0], [0,1,0],[0,0,-1]])

In [7]:
values, vectors = np.linalg.eig(B)

In [8]:
print(values)

[ 2.  1. -1.]
